### ISSUE TITLE
any plans on upgrading for angular v4?

### ISSUE THREAD

**Issue by emreavsar** [zztop101/ng-password-helper#2]
after upgrading from angular 2.3 to angular 4 i've got this problem:

`
ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in myproject/node_modules/ng-password-helper/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in myproject/node_modules/ng-password-helper/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in myproject/node_modules/ng-password-helper/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in myproject/node_modules/ng-password-helper/node_modules/@angular/core/index.d.ts, resolving symbol NgPasswordHelperModule in myproject/node_modules/ng-password-helper/dist/index.d.ts, resolving symbol NgPasswordHelperModule in myproject/node_modules/ng-password-helper/dist/index.d.ts
webpack: Failed to compile.
`
most probably because of AOT.

**Comment by zztop101** [comment]
Hi, Thanks for the feedback.  I have upgraded to angular V4 - please try it out.

**Comment by emreavsar** [comment]
Works perfectly. thanks!
