### ISSUE TITLE
support for angular v5.0.0

### ISSUE THREAD

**Issue by emreavsar** [zztop101/ng-password-helper#3]
hi i just updated to v5.0.0 of angular and getting issues like these:

```
webpack-internal:///../../../core/esm5/core.js:1546 ERROR Error: Uncaught (in promise): Error: Unexpected value 'NgPasswordHelperModule' imported by the module 'SignupModule'. Please add a @NgModule annotation.
Error: Unexpected value 'NgPasswordHelperModule' imported by the module 'SignupModule'. Please add a @NgModule annotation.
```

_FYI: Maybe this issue is related to https://github.com/angular/angular-cli/issues/8391_

**Comment by zztop101** [comment]
Hi, I updated to angular 5 in my demo app and was able to recreate the same issue. I haven't had a chance to fix it though. I'll try and take a look at it some time during the week.

**Comment by emreavsar** [comment]
Alright. Really appreciate a solution here. Otherwise we have to remove the password helper from our app...

**Comment by zztop101** [comment]
Hi, Sorry for the long delay, I hope you have not removed the module from your project. I had a lot of issues with this and have rewritten how I build the module using 
[generator-angular2-library](https://github.com/jvandemo/generator-angular2-library). My initial test shows that it is working. Can you try it out ?  delete the module and install the latest version (5.0.1).
If you have the same issue, try running your project with ng serve --preserve-symlink to see if it fixes it.

**Comment by emreavsar** [comment]
worked out pretty well with 5.0.3, thanks!
